version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: dogwalk-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: DogWalkService
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: